### ISSUE TITLE
Trouble uploading dSYMs 

### ISSUE THREAD

**Issue by tshort15-ford** [DataDog/datadog-fastlane-plugin#5]
I'm trying to see if Datadog can symbolicate crash reports and I have tried successfully to upload using this plugin when running locally on a directory of dSYMs, but on CI I get an error with `FastlaneShellError`:

```
[2022-02-22T11:30:04.807Z] /Users/anka/.rvm/gems/ruby-2.7.2/gems/fastlane-plugin-datadog-0.2.0/lib/fastlane/plugin/datadog/actions/upload_symbols_to_datadog.rb:18:in `rescue in block in run': \e[31m[!] uninitialized constant Fastlane::Actions::UploadSymbolsToDatadogAction::FastlaneShellError (NameError)
[2022-02-22T11:30:04.807Z] Did you mean?  FastlaneCore\e[0m
[2022-02-22T11:30:04.807Z] Did you mean?  FastlaneCore
[2022-02-22T11:30:04.807Z] 	from /Users/anka/.rvm/gems/ruby-2.7.2/gems/fastlane-plugin-datadog-0.2.0/lib/fastlane/plugin/datadog/actions/upload_symbols_to_datadog.rb:17:in `block in run'
[2022-02-22T11:30:04.807Z] 	from /Users/anka/.rvm/gems/ruby-2.7.2/gems/fastlane-plugin-datadog-0.2.0/lib/fastlane/plugin/datadog/actions/upload_symbols_to_datadog.rb:16:in `each'
[2022-02-22T11:30:04.807Z] 	from /Users/anka/.rvm/gems/ruby-2.7.2/gems/fastlane-plugin-datadog-0.2.0/lib/fastlane/plugin/datadog/actions/upload_symbols_to_datadog.rb:16:in `run'
[2022-02-22T11:30:04.807Z] 	from /Users/anka/.rvm/gems/ruby-2.7.2/gems/fastlane-2.204.3/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'

```

I'm sure the `key` is correct so I'm wondering if there is something wrong with my dsym_path below:

```
dsym_path = "./build/UAT/App.xcarchive/dSYMs/"
upload_symbols_to_datadog(api_key: key, dsym_paths: [dsym_path])

```

I've tried with a zip of the dSYMs too but same result.  Any ideas?

**Comment by tshort15-ford** [comment]
We didn't have npx on the CI system, so resolved by installing node.

**Comment by SVMichael** [comment]
it would be nice if they will include this as prerequisite from the readme. thanks for the info.
