### ISSUE TITLE
Upload dsyms to Datadog fails

### ISSUE THREAD

**Issue by ooemil** [DataDog/datadog-fastlane-plugin#6]
Trying to upload dsyms to Datadog (eu) using fastlane fails with following output.
What am I doing wrong?

```
Looking for related GitHub issues on fastlane/fastlane...

➡️  Specify IPA path as a parameter to deliver beta
    https://github.com/fastlane/fastlane/issues/244 [closed] 2 💬
    22 Sep 2016

➡️  commit_version_bump error in-spite of expected and actual changes being same
    https://github.com/fastlane/fastlane/issues/248 [closed] 2 💬
    22 Sep 2016

➡️  Sigh: Lane specific `team_id` and `app_identifier` not used
    https://github.com/fastlane/fastlane/issues/256 [closed] 23 💬
    22 Sep 2016

and 19128 more at: https://github.com/fastlane/fastlane/search?q=uninitialized%20constant%20Fastlane%3A%3AActions%3A%3AUploadSymbolsToDatadogAction%3A%3AFastlaneShellError%0A%0A%20%20%20%20%20%20%20%20rescue%20FastlaneShellError%20%3D%3E%20e%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0ADid%20you%20mean%3F%20%20FastlaneCore&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-plugin-datadog-0.2.0/lib/fastlane/plugin/datadog/actions/upload_symbols_to_datadog.rb:18:in `rescue in block in run': \e[31m[!] uninitialized constant Fastlane::Actions::UploadSymbolsToDatadogAction::FastlaneShellError (NameError)

        rescue FastlaneShellError => e
               ^^^^^^^^^^^^^^^^^^
Did you mean?  FastlaneCore\e[0m
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-plugin-datadog-0.2.0/lib/fastlane/plugin/datadog/actions/upload_symbols_to_datadog.rb:17:in `block in run'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-plugin-datadog-0.2.0/lib/fastlane/plugin/datadog/actions/upload_symbols_to_datadog.rb:16:in `each'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-plugin-datadog-0.2.0/lib/fastlane/plugin/datadog/actions/upload_symbols_to_datadog.rb:16:in `run'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:394:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/bin/fastlane:25:in `<main>'
/opt/homebrew/Cellar/ruby/3.1.0/lib/ruby/3.1.0/open3.rb:222:in `spawn': No such file or directory - npx (Errno::ENOENT)
	from /opt/homebrew/Cellar/ruby/3.1.0/lib/ruby/3.1.0/open3.rb:222:in `popen_run'
	from /opt/homebrew/Cellar/ruby/3.1.0/lib/ruby/3.1.0/open3.rb:210:in `popen2e'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
	from /opt/homebrew/Cellar/ruby/3.1.0/lib/ruby/3.1.0/forwardable.rb:238:in `sh'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-plugin-datadog-0.2.0/lib/fastlane/plugin/datadog/actions/upload_symbols_to_datadog.rb:32:in `upload_path'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-plugin-datadog-0.2.0/lib/fastlane/plugin/datadog/actions/upload_symbols_to_datadog.rb:17:in `block in run'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-plugin-datadog-0.2.0/lib/fastlane/plugin/datadog/actions/upload_symbols_to_datadog.rb:16:in `each'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-plugin-datadog-0.2.0/lib/fastlane/plugin/datadog/actions/upload_symbols_to_datadog.rb:16:in `run'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:394:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/gems/fastlane-2.207.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/bin/fastlane:25:in `load'
	from /opt/homebrew/Cellar/fastlane/2.204.3/libexec/bin/fastlane:25:in `<main>'
```

The lane used:

```
desc "Upload dsyms to datadog"
    lane :upload_dsym_with_download_dsyms do
        download_dsyms(app_identifier: "dk.ooono.connect", after_uploaded_date: "2022-06-21T19:00:00+01:00")
	  upload_symbols_to_datadog(
	    api_key: "HIDDEN",
	    site: 'datadoghq.eu', dry_run: true
	  )
    end
```

Result of env
```
__CFBundleIdentifier=com.apple.Terminal
TMPDIR=/var/folders/z9/_4p1c2n52tv2jg2sbvbz56d00000gn/T/
XPC_FLAGS=0x0
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.9s1A2Qb2aC/Listeners
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=445
TERM_SESSION_ID=A6D1EEA9-A6C4-464C-83B4-48F277C340F9
SHELL=/bin/zsh
HOME=/Users/emilandersen
LOGNAME=emilandersen
USER=emilandersen
PATH=/var/folders/z9/_4p1c2n52tv2jg2sbvbz56d00000gn/T/frum_63247_1657266832089/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/emilandersen/.rvm/bin
SHLVL=1
PWD=/Users/emilandersen/Desktop/OOONO/iOS-OOONO
OLDPWD=/Users/emilandersen
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
MANPATH=/opt/homebrew/share/man::
INFOPATH=/opt/homebrew/share/info:
ZSH=/Users/emilandersen/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
FRUM_MULTISHELL_PATH=/var/folders/z9/_4p1c2n52tv2jg2sbvbz56d00000gn/T/frum_63247_1657266832089
FRUM_DIR=/Users/emilandersen/.frum
FRUM_LOGLEVEL=info
FRUM_RUBY_BUILD_MIRROR=https://cache.ruby-lang.org/pub/ruby
rvm_prefix=/Users/emilandersen
rvm_path=/Users/emilandersen/.rvm
rvm_bin_path=/Users/emilandersen/.rvm/bin
rvm_version=1.29.12-next (master)
rvm_alias_expanded=
rvm_bin_flag=
rvm_docs_type=
rvm_gemstone_package_file=
rvm_gemstone_url=
rvm_niceness=
rvm_nightly_flag=
rvm_only_path_flag=
rvm_pretty_print_flag=
rvm_proxy=
rvm_quiet_flag=
rvm_ruby_bits=
rvm_ruby_file=
rvm_ruby_make=
rvm_ruby_make_install=
rvm_ruby_mode=
rvm_script_name=
rvm_sdk=
rvm_silent_flag=
rvm_use_flag=
rvm_hook=
LC_CTYPE=UTF-8
_=/usr/bin/env
```

Content of Pluginfile:
```
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-datadog'
````

Content of Gemfile
```
source "https://rubygems.org"

gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
```

**Comment by maxep** [comment]
Hi @ooemil 

Thank you for the report! Looks like the plugin cannot run the `npx` command, do you have `Node.js` installed on your machine?
This plugin uses [`datadog-ci`](https://github.com/DataDog/datadog-ci/blob/master/src/commands/dsyms/README.md) to upload the dSYMs, it's a `npm` package that requires `Node.js` to be installed.
I don't see it explicitly mentioned in the README, so we probably should add that.

Let me know if that fixes your issue.
